openapi: 3.0.0
info:
  title: Subunit Todo API
  version: 1.0.0
servers:
  - url: https://subunit_todo.koron-konan123.workers.dev/v1/api
    description: 開発環境
paths:
  /todo:
    get:
      tags: 
        - todo
      summary: Todoを一覧取得
      description: Get all Todo
      parameters: []
      responses:
        '200':
          description: GET ALL
          content:
            application/json:
              schema: 
                type: object
                properties:
                  todo: 
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - title
                        - completed
                      properties:
                        id: 
                          type: string
                        title:
                          type: string
                        completed:
                          type: boolean
                example:
                  todo: 
                    - id: "1234567890"
                      title: John Doe
                      completed: false
                    - id: "0987654321"
                      title: Jane Doe
                      completed: true
    post:
      tags: 
        - todo
      summary: Todoを作成
      description: Create a new Todo
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
            example:
              title: Create Todo
      responses:
        '201':
          description: CREATED
  /todo/{id}:
    put:
      tags: 
        - todo
      summary: Todoのタイトルを更新
      description: Update Todo title
      parameters:
        - name: id
          in: path
          description: Todoのid
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
            example:
              title: Update Todo title
      responses:
        '201':
          description: UPDATED
    delete:
      tags: 
        - todo
      summary: Todoを削除
      description: Delete a Todo
      parameters:
        - name: id
          in: path
          description: Todoのid
          required: true
          schema:
            type: string
      responses:
        '201':
          description: DELETED
  /todo/{id}/completed:
    put:
      tags: 
        - todo
      summary: Todoの完了済みフラグを更新
      description: Update Todo completed
      parameters:
        - name: id
          in: path
          description: Todoのid
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - completed
              properties:
                completed:
                  type: boolean
            example:
              completed: true
      responses:
        '201':
          description: UPDATED
